### ISSUE TITLE
fill/brush color not working

### ISSUE THREAD

**Issue by cryptic-rat16** [UjwalKandi/Issue-Bookmarks#389]
Unable to change color for brush. Only tool functioning is pencil.

**Comment by cryptic-rat16** [comment]
HI,
I am not asking - a request. I am reporting a bug. Still the same. The color cannot be changed, it is stuck on the same color as the background. So - makes it useless. What would you like me to send you?
This btw is since the update. Before that I used for the last 2 years to create images.
I am not a programmer, just a user of the Beta.

Thanks.

**Comment by UjwalKandi** [comment]
Hi @cryptic-rat16,

Can you add the screenshot/URL of the site so that I can understand your issue more precisely?

Thanks!
